CREATE TABLE questions (
    qid INTEGER PRIMARY KEY AUTOINCREMENT,
    question TEXT,
    madeOn INTERGER default CURRENT_TIMESTAMP
);

CREATE TABLE options (
    oid INTEGER PRIMARY KEY ASC,
    qid INTEGER
    option TEXT
);

CREATE TABLE vote (
    vid INTEGER PRIMARY KEY ASC,
    oid INTEGER,
    voteDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);