CREATE TABLE questions (
    qid INTEGER PRIMARY KEY AUTOINCREMENT,
    question TEXT,
    madeOn INTERGER default CURRENT_TIMESTAMP
);

CREATE TABLE options (
    oid INTERGER PRIMARY KEY ASC,
    option TEXT
);

CREATE TABLE vote (
    vid INTERGER PRIMARY KEY ASC,
    oid INTERGER,
    voteDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);